# Cloud18 sample PHP application: nginx site of the signal18/php-fpm-84 image,
# mounted on /etc/nginx/sites-available/default by the php template.
server {
    listen       80;
    listen  [::]:80;
    server_name  _;

    root   /var/www/html;
    index  index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass   unix:/var/run/php-fpm.sock;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\. {
        deny all;
    }
}
